name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  ci-test:
    name: test
    strategy:
      matrix:
        go: [1.18]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - name: Test
      run: go test -v ./...

  golangci:
    name: lint
    strategy:
      matrix:
        go: [1.18]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
